### CreateWarehouse
POST http://localhost:8080/create-warehouse HTTP/1.1
Content-Type: application/json

{
    "name": "2",
    "is_available": true
}


### CreateProduct
POST http://localhost:8080/create-product
Content-Type: application/json

{
    "name": "Product 3",
    "size": 12.34,
    "code": "ABC12311",
    "quantity": 56,
    "warehouse_id": 2
}



### ReserveProducts
POST http://localhost:8080/reserve-products HTTP/1.1
Content-Type: application/json

["ABC123", "ABC1231"]




### ReleaseProducts
POST http://localhost:8080/release-products HTTP/1.1
Content-Type: application/json

["ABC123", "ABC1231"]




### GetRemainingProducts
GET http://localhost:8080/remaining-products/2

