basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a sample API for a warehouse application
  title: Warehouse API Documentation
  version: "1"
paths: {}
swagger: "2.0"
